name = "id" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "www.facebook.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "gogan.gojek.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "m.youtube.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "api.joox.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "v.whatsapp.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "api.spotify.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "api.tiktokcdn.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "autodiscover.instagram.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "m.instagram.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "hwvip.iflix.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "z-p15.www.instagram.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.id.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "api-gateway-global.viu.com.id.aghill.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "2227bdd6-5333-4a6b-b57b-9a7cee755268"
